const restful = require('node-restful')
const mongoose = restful.mongoose

const curtiDemaisSchema = new mongoose.Schema({
  id: { type: Number },
  title: { type: String },
  description: { type: String },
  width: { type: Number },
  height: { type: Number },
  images:
   { hidpi:  { type: String },
     normal: { type: String },
     teaser: { type: String },
    },
  views_count: { type: Number },
  likes_count: { type: Number },
  comments_count: { type: Number },
  attachments_count: { type: Number },
  rebounds_count: { type: Number },
  buckets_count: { type: Number },
  created_at: { type: String },
  updated_at: { type: String },
  html_url: { type: String },
  attachments_url: { type: String },
  buckets_url: { type: String },
  comments_url: { type: String },
  likes_url: { type: String },
  projects_url: { type: String },
  rebounds_url: { type: String },
  rebound_source_url: { type: String },
  animated: { type: Boolean },
  tags: {type: Array, default: []},
  user:
   { id: { type: Number },
     name: { type: String },
     username: { type: String },
     html_url: { type: String },
     avatar_url: { type: String },
     bio: { type: String },
     location: { type: String },
     links:
      { web: { type: String },
        twitter: { type: String } 
      },
     buckets_count: { type: Number },
     comments_received_count: { type: Number },
     followers_count: { type: Number },
     followings_count: { type: Number },
     likes_count: { type: Number },
     likes_received_count: { type: Number },
     projects_count: { type: Number },
     rebounds_received_count: { type: Number },
     shots_count: { type: Number },
     teams_count: { type: Number },
     can_upload_shot: { type: Boolean },
     type: { type: String },
     pro: { type: Boolean },
     buckets_url: { type: String },
     followers_url: { type: String },
     following_url: { type: String },
     likes_url: { type: String },
     projects_url: { type: String },
     shots_url: { type: String },
     teams_url: { type: String },
     created_at: { type: String },
     updated_at: { type: String },
   },
  team:
   { id: { type: Number },
     name: { type: String },
     username: { type: String },
     html_url: { type: String },
     avatar_url: { type: String },
     bio: { type: String },
     location: { type: String },
     links:
      { web: { type: String },
        twitter: { type: String },
      },
     buckets_count: { type: Number },
     comments_received_count: { type: Number },
     followers_count: { type: Number },
     followings_count: { type: Number },
     likes_count: { type: Number },
     likes_received_count: { type: Number },
     projects_count: { type: Number },
     rebounds_received_count: { type: Number },
     shots_count: { type: Number },
     can_upload_shot: { type: Boolean },
     type: { type: String },
     pro: { type: Boolean },
     buckets_url: { type: String },
     followers_url: { type: String },
     following_url: { type: String },
     likes_url: { type: String },
     projects_url: { type: String },
     shots_url: { type: String },
     created_at: { type: String },
     updated_at: { type: String },
     members_count: { type: Number },
     members_url: { type: String },
     team_shots_url: { type: String },
    }, 

})

module.exports = restful.model('CurtiDemais', curtiDemaisSchema)

